import Foundation

/// Generates daily Markdown reports summarizing eye health metrics.
///
/// Reports are saved to `~/EyeGuard/reports/YYYY-MM-DD.md`.
struct DailyReportGenerator {

    private let calculator = HealthScoreCalculator()

    /// Generates and saves a daily report for the given data.
    ///
    /// - Parameters:
    ///   - date: The date of the report.
    ///   - sessions: Usage sessions for the day.
    ///   - breakEvents: All break events for the day.
    ///   - totalScreenTime: Total active screen time in seconds.
    ///   - longestContinuousSession: Longest unbroken session in seconds.
    /// - Returns: The generated `DailyReport` struct.
    func generate(
        date: Date = .now,
        sessions: [UsageSession],
        breakEvents: [BreakEvent],
        totalScreenTime: TimeInterval,
        longestContinuousSession: TimeInterval
    ) -> DailyReport {
        let healthScore = calculator.calculate(
            breakEvents: breakEvents,
            totalScreenTime: totalScreenTime,
            longestContinuousSession: longestContinuousSession
        )

        let takenCount = breakEvents.filter(\.wasTaken).count
        let report = DailyReport(
            date: date,
            sessions: sessions,
            healthScore: healthScore,
            totalScreenTime: totalScreenTime,
            totalBreaksTaken: takenCount,
            totalBreaksScheduled: breakEvents.count
        )

        saveMarkdownReport(report, date: date)
        return report
    }

    // MARK: - Markdown Generation

    /// Saves the report as a Markdown file.
    private func saveMarkdownReport(_ report: DailyReport, date: Date) {
        let markdown = renderMarkdown(report, date: date)
        let fileName = "\(report.dateString).md"
        let fileURL = EyeGuardConstants.reportsDirectory.appendingPathComponent(fileName)

        do {
            let directory = fileURL.deletingLastPathComponent()
            try FileManager.default.createDirectory(
                at: directory,
                withIntermediateDirectories: true
            )
            try markdown.write(to: fileURL, atomically: true, encoding: .utf8)
            print("[DailyReportGenerator] Report saved: \(fileURL.path)")
        } catch {
            print("[DailyReportGenerator] Failed to save report: \(error.localizedDescription)")
        }
    }

    /// Renders a `DailyReport` as a Markdown string.
    private func renderMarkdown(_ report: DailyReport, date: Date) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .long

        let score = report.healthScore
        let screenTimeStr = formatDuration(report.totalScreenTime)

        return """
        # EyeGuard Daily Report — \(dateFormatter.string(from: date))

        ## Health Score: \(score.totalScore)/100 \(healthEmoji(score.totalScore))

        | Component | Score | Max |
        |-----------|-------|-----|
        | Break Compliance | \(score.breakCompliance) | 40 |
        | Continuous Use Discipline | \(score.continuousUseDiscipline) | 30 |
        | Screen Time | \(score.screenTimeScore) | 20 |
        | Break Quality | \(score.breakQuality) | 10 |

        ## Summary

        - **Total Screen Time**: \(screenTimeStr)
        - **Breaks Taken**: \(report.totalBreaksTaken) / \(report.totalBreaksScheduled)
        - **Sessions**: \(report.sessions.count)

        ## Break Details

        | Time | Type | Taken | Duration |
        |------|------|-------|----------|
        \(renderBreakRows(report.sessions))

        ## Recommendations

        \(generateRecommendations(score))

        ---
        *Generated by EyeGuard*
        """
    }

    private func renderBreakRows(_ sessions: [UsageSession]) -> String {
        let allBreaks = sessions.flatMap(\.breaks)
        if allBreaks.isEmpty {
            return "| — | No breaks recorded | — | — |"
        }

        let timeFormatter = DateFormatter()
        timeFormatter.timeStyle = .short

        return allBreaks.map { event in
            let time = timeFormatter.string(from: event.timestamp)
            let taken = event.wasTaken ? "Yes" : "No"
            let duration = event.wasTaken ? formatDuration(event.actualDuration) : "—"
            return "| \(time) | \(event.type.displayName) | \(taken) | \(duration) |"
        }.joined(separator: "\n")
    }

    private func generateRecommendations(_ score: HealthScore) -> String {
        var recommendations: [String] = []

        if score.breakCompliance < 30 {
            recommendations.append(
                "- Take more breaks. Try not to skip break notifications."
            )
        }
        if score.continuousUseDiscipline < 20 {
            recommendations.append(
                "- Avoid long unbroken sessions. Stand up at least every 2 hours."
            )
        }
        if score.screenTimeScore < 15 {
            recommendations.append(
                "- Consider reducing total screen time. Aim for under 8 hours."
            )
        }
        if score.breakQuality < 7 {
            recommendations.append(
                "- When you take a break, make it count. Look away for the full duration."
            )
        }

        if recommendations.isEmpty {
            return "Great job! Keep maintaining your healthy screen habits."
        }

        return recommendations.joined(separator: "\n")
    }

    // MARK: - Helpers

    private func formatDuration(_ interval: TimeInterval) -> String {
        let totalSeconds = Int(interval)
        let hours = totalSeconds / 3600
        let minutes = (totalSeconds % 3600) / 60

        if hours > 0 {
            return "\(hours)h \(minutes)m"
        }
        return "\(minutes)m"
    }

    private func healthEmoji(_ score: Int) -> String {
        switch score {
        case 80...100: return ""
        case 60..<80:  return ""
        case 40..<60:  return ""
        default:       return ""
        }
    }
}
