import Foundation
import Testing

@testable import EyeGuard

// MARK: - UserPreferencesManager Tests

@Suite("UserPreferencesManager", .serialized)
struct UserPreferencesManagerTests {

    /// Helper to set and synchronize UserDefaults in test environment.
    private func setDefault(_ value: Any, forKey key: String) {
        UserDefaults.standard.set(value, forKey: key)
        UserDefaults.standard.synchronize()
    }

    private func removeDefault(forKey key: String) {
        UserDefaults.standard.removeObject(forKey: key)
        UserDefaults.standard.synchronize()
    }

    private let breakKeys = [
        "microBreakIntervalMinutes",
        "macroBreakIntervalMinutes",
        "mandatoryBreakIntervalMinutes",
        "microBreakDurationSeconds",
        "macroBreakDurationMinutes",
        "mandatoryBreakDurationMinutes",
        "isNotificationSoundEnabled",
    ]

    @Test("Load returns default values when no UserDefaults set")
    func loadDefaults() {
        // Clear any existing keys to test defaults
        for key in breakKeys {
            removeDefault(forKey: key)
        }

        let prefs = UserPreferencesManager.load()

        // Default micro: 20 min interval, 20 sec duration
        #expect(prefs.microBreakInterval == 20 * 60)
        #expect(prefs.microBreakDuration == 20)

        // Default macro: 60 min interval, 5 min duration
        #expect(prefs.macroBreakInterval == 60 * 60)
        #expect(prefs.macroBreakDuration == 5 * 60)

        // Default mandatory: 120 min interval, 15 min duration
        #expect(prefs.mandatoryBreakInterval == 120 * 60)
        #expect(prefs.mandatoryBreakDuration == 15 * 60)

        // Default sound: enabled
        #expect(prefs.isSoundEnabled == true)
    }

    @Test("Load reads custom micro interval from UserDefaults")
    func loadCustomMicroInterval() {
        setDefault(25.0, forKey: "microBreakIntervalMinutes")
        let prefs = UserPreferencesManager.load()
        #expect(prefs.microBreakInterval == 25 * 60)
        removeDefault(forKey: "microBreakIntervalMinutes")
    }

    @Test("Load reads custom micro duration from UserDefaults")
    func loadCustomMicroDuration() {
        // Set, synchronize, then read immediately to avoid race with parallel tests
        let key = "microBreakDurationSeconds"
        UserDefaults.standard.set(30.0, forKey: key)
        UserDefaults.standard.synchronize()
        let storedValue = UserDefaults.standard.double(forKey: key)
        // Verify UserDefaults actually stored the value before testing the manager
        #expect(storedValue == 30.0)
        if storedValue == 30.0 {
            let prefs = UserPreferencesManager.load()
            #expect(prefs.microBreakDuration == 30)
        }
        UserDefaults.standard.removeObject(forKey: key)
        UserDefaults.standard.synchronize()
    }

    @Test("Load reads custom sound setting from UserDefaults")
    func loadCustomSound() {
        setDefault(false, forKey: "isNotificationSoundEnabled")
        let prefs = UserPreferencesManager.load()
        #expect(prefs.isSoundEnabled == false)
        removeDefault(forKey: "isNotificationSoundEnabled")
    }

    @Test("Auto report enabled returns true by default")
    func autoReportDefault() {
        removeDefault(forKey: "autoGenerateDailyReport")
        #expect(UserPreferencesManager.isAutoReportEnabled == true)
    }

    @Test("Auto report enabled reflects UserDefaults value")
    func autoReportCustom() {
        setDefault(false, forKey: "autoGenerateDailyReport")
        #expect(UserPreferencesManager.isAutoReportEnabled == false)
        removeDefault(forKey: "autoGenerateDailyReport")
    }

    @Test("Launch at login returns false by default")
    func launchAtLoginDefault() {
        removeDefault(forKey: "launchAtLogin")
        #expect(UserPreferencesManager.isLaunchAtLoginEnabled == false)
    }

    @Test("Launch at login reflects UserDefaults value")
    func launchAtLoginCustom() {
        setDefault(true, forKey: "launchAtLogin")
        #expect(UserPreferencesManager.isLaunchAtLoginEnabled == true)
        removeDefault(forKey: "launchAtLogin")
    }

    @Test("All break types remain enabled")
    func breakTypesEnabled() {
        let prefs = UserPreferencesManager.load()
        #expect(prefs.isMicroBreakEnabled == true)
        #expect(prefs.isMacroBreakEnabled == true)
        #expect(prefs.isMandatoryBreakEnabled == true)
    }

    @Test("Escalation is always enabled")
    func escalationEnabled() {
        let prefs = UserPreferencesManager.load()
        #expect(prefs.isEscalationEnabled == true)
    }
}
