import SwiftUI

/// SwiftUI preferences window with sections for break intervals, durations,
/// notifications, general settings, and report configuration.
///
/// Uses @AppStorage for UserDefaults persistence. Values are read by
/// BreakScheduler on next initialization or via live binding.
struct PreferencesView: View {

    // MARK: - Break Intervals (stored in minutes, displayed as minutes)

    @AppStorage("microBreakIntervalMinutes")
    private var microBreakIntervalMinutes: Double = 20

    @AppStorage("macroBreakIntervalMinutes")
    private var macroBreakIntervalMinutes: Double = 60

    @AppStorage("mandatoryBreakIntervalMinutes")
    private var mandatoryBreakIntervalMinutes: Double = 120

    // MARK: - Break Durations (stored in seconds)

    @AppStorage("microBreakDurationSeconds")
    private var microBreakDurationSeconds: Double = 20

    @AppStorage("macroBreakDurationMinutes")
    private var macroBreakDurationMinutes: Double = 5

    @AppStorage("mandatoryBreakDurationMinutes")
    private var mandatoryBreakDurationMinutes: Double = 15

    // MARK: - Notifications

    @AppStorage("isTier1NotificationsEnabled")
    private var isTier1Enabled: Bool = true

    @AppStorage("isTier2NotificationsEnabled")
    private var isTier2Enabled: Bool = true

    @AppStorage("isTier3NotificationsEnabled")
    private var isTier3Enabled: Bool = true

    @AppStorage("isNotificationSoundEnabled")
    private var isSoundEnabled: Bool = true

    // MARK: - General

    @AppStorage("launchAtLogin")
    private var launchAtLogin: Bool = false

    @AppStorage("showInDock")
    private var showInDock: Bool = false

    // MARK: - Reports

    @AppStorage("autoGenerateDailyReport")
    private var autoGenerateReport: Bool = true

    @AppStorage("reportDirectory")
    private var reportDirectory: String = EyeGuardConstants.reportsDirectory.path

    var body: some View {
        TabView {
            breakIntervalsTab
                .tabItem {
                    Label("Breaks", systemImage: "clock")
                }

            notificationsTab
                .tabItem {
                    Label("Notifications", systemImage: "bell")
                }

            generalTab
                .tabItem {
                    Label("General", systemImage: "gear")
                }

            reportsTab
                .tabItem {
                    Label("Reports", systemImage: "doc.text")
                }
        }
        .frame(width: 480, height: 420)
        .padding()
    }

    // MARK: - Break Intervals Tab

    private var breakIntervalsTab: some View {
        Form {
            Section {
                intervalSlider(
                    title: "Micro Break Interval",
                    value: $microBreakIntervalMinutes,
                    range: 10...30,
                    unit: "minutes",
                    description: "20-20-20 rule: Look 20 ft away every 20 min"
                )

                durationSlider(
                    title: "Micro Break Duration",
                    value: $microBreakDurationSeconds,
                    range: 10...60,
                    unit: "seconds",
                    description: "How long to rest your eyes"
                )
            } header: {
                Label("Micro Break (20-20-20 Rule)", systemImage: "eye")
            }

            Section {
                intervalSlider(
                    title: "Macro Break Interval",
                    value: $macroBreakIntervalMinutes,
                    range: 30...90,
                    unit: "minutes",
                    description: "OSHA recommendation: break every 60 min"
                )

                durationSlider(
                    title: "Macro Break Duration",
                    value: $macroBreakDurationMinutes,
                    range: 3...15,
                    unit: "minutes",
                    description: "Get up, stretch, move around"
                )
            } header: {
                Label("Macro Break (Hourly)", systemImage: "cup.and.saucer")
            }

            Section {
                intervalSlider(
                    title: "Mandatory Break Interval",
                    value: $mandatoryBreakIntervalMinutes,
                    range: 60...180,
                    unit: "minutes",
                    description: "EU directive: max 2 hours continuous use"
                )

                durationSlider(
                    title: "Mandatory Break Duration",
                    value: $mandatoryBreakDurationMinutes,
                    range: 10...30,
                    unit: "minutes",
                    description: "A full reset: walk, hydrate, rest eyes"
                )
            } header: {
                Label("Mandatory Break (Extended)", systemImage: "figure.walk")
            }

            Section {
                HStack {
                    Spacer()
                    Button("Reset to Defaults") {
                        resetBreakDefaults()
                    }
                    .foregroundStyle(.secondary)
                }
            }
        }
        .formStyle(.grouped)
    }

    // MARK: - Notifications Tab

    private var notificationsTab: some View {
        Form {
            Section {
                Toggle(isOn: $isTier1Enabled) {
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Tier 1 — Gentle Notification")
                            .font(.body)
                        Text("macOS notification center banner")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }

                Toggle(isOn: $isTier2Enabled) {
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Tier 2 — Floating Overlay")
                            .font(.body)
                        Text("Floating window reminder on screen")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }

                Toggle(isOn: $isTier3Enabled) {
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Tier 3 — Full-Screen Overlay")
                            .font(.body)
                        Text("Full-screen break enforcement for mandatory breaks")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
            } header: {
                Label("Notification Tiers", systemImage: "bell.badge")
            }

            Section {
                Toggle("Notification Sound", isOn: $isSoundEnabled)
            } header: {
                Label("Sound", systemImage: "speaker.wave.2")
            }
        }
        .formStyle(.grouped)
    }

    // MARK: - General Tab

    private var generalTab: some View {
        Form {
            Section {
                Toggle("Launch at Login", isOn: $launchAtLogin)
                    .onChange(of: launchAtLogin) { _, newValue in
                        handleLaunchAtLoginChange(newValue)
                    }

                Toggle(isOn: $showInDock) {
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Show in Dock")
                            .font(.body)
                        Text("EyeGuard is a menu bar app by default")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
            } header: {
                Label("Startup", systemImage: "power")
            }

            Section {
                VStack(alignment: .leading, spacing: 4) {
                    Text("EyeGuard v0.8")
                        .font(.headline)
                    Text("Protect your eyes with science-based break reminders")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            } header: {
                Label("About", systemImage: "info.circle")
            }
        }
        .formStyle(.grouped)
    }

    // MARK: - Reports Tab

    private var reportsTab: some View {
        Form {
            Section {
                Toggle("Auto-Generate Daily Report", isOn: $autoGenerateReport)

                VStack(alignment: .leading, spacing: 4) {
                    Text("Report Directory")
                        .font(.body)
                    Text(reportDirectory)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                        .lineLimit(2)
                        .truncationMode(.middle)

                    Button("Open in Finder") {
                        let url = URL(fileURLWithPath: reportDirectory)
                        NSWorkspace.shared.open(url)
                    }
                    .font(.caption)
                }
            } header: {
                Label("Daily Reports", systemImage: "doc.text")
            }
        }
        .formStyle(.grouped)
    }

    // MARK: - Slider Helpers

    private func intervalSlider(
        title: String,
        value: Binding<Double>,
        range: ClosedRange<Double>,
        unit: String,
        description: String
    ) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack {
                Text(title)
                Spacer()
                Text("\(Int(value.wrappedValue)) \(unit)")
                    .font(.system(.body, design: .monospaced))
                    .foregroundStyle(.blue)
            }

            Slider(value: value, in: range, step: 5) {
                Text(title)
            } minimumValueLabel: {
                Text("\(Int(range.lowerBound))")
                    .font(.caption2)
            } maximumValueLabel: {
                Text("\(Int(range.upperBound))")
                    .font(.caption2)
            }

            Text(description)
                .font(.caption)
                .foregroundStyle(.secondary)
        }
    }

    private func durationSlider(
        title: String,
        value: Binding<Double>,
        range: ClosedRange<Double>,
        unit: String,
        description: String
    ) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack {
                Text(title)
                Spacer()
                Text("\(Int(value.wrappedValue)) \(unit)")
                    .font(.system(.body, design: .monospaced))
                    .foregroundStyle(.blue)
            }

            Slider(value: value, in: range, step: 1) {
                Text(title)
            } minimumValueLabel: {
                Text("\(Int(range.lowerBound))")
                    .font(.caption2)
            } maximumValueLabel: {
                Text("\(Int(range.upperBound))")
                    .font(.caption2)
            }

            Text(description)
                .font(.caption)
                .foregroundStyle(.secondary)
        }
    }

    // MARK: - Actions

    private func resetBreakDefaults() {
        microBreakIntervalMinutes = 20
        microBreakDurationSeconds = 20
        macroBreakIntervalMinutes = 60
        macroBreakDurationMinutes = 5
        mandatoryBreakIntervalMinutes = 120
        mandatoryBreakDurationMinutes = 15
    }

    private func handleLaunchAtLoginChange(_ enabled: Bool) {
        // Launch-at-login registration would use SMAppService on macOS 13+
        // For now, just persist the preference
        Log.app.info("Launch at login \(enabled ? "enabled" : "disabled")")
    }
}
