import Foundation
import os

/// Reads user preferences from UserDefaults (@AppStorage) and converts
/// them to a `UserPreferences` struct for use by BreakScheduler.
///
/// Provides a bridge between the SwiftUI @AppStorage values in
/// PreferencesView and the value-type UserPreferences used by the scheduler.
enum UserPreferencesManager {

    /// Loads preferences from UserDefaults, falling back to defaults.
    static func load() -> UserPreferences {
        let defaults = UserDefaults.standard

        let microInterval = defaults.double(forKey: "microBreakIntervalMinutes")
        let macroInterval = defaults.double(forKey: "macroBreakIntervalMinutes")
        let mandatoryInterval = defaults.double(forKey: "mandatoryBreakIntervalMinutes")
        let microDuration = defaults.double(forKey: "microBreakDurationSeconds")
        let macroDuration = defaults.double(forKey: "macroBreakDurationMinutes")
        let mandatoryDuration = defaults.double(forKey: "mandatoryBreakDurationMinutes")
        let soundEnabled = defaults.object(forKey: "isNotificationSoundEnabled")

        // Load reminder mode (v2.4), default to aggressive
        let reminderMode: ReminderMode
        if let modeString = defaults.string(forKey: "reminderMode"),
           let mode = ReminderMode(rawValue: modeString) {
            reminderMode = mode
        } else {
            reminderMode = EyeGuardConstants.defaultReminderMode
        }

        return UserPreferences(
            microBreakInterval: (microInterval > 0 ? microInterval : 20) * 60,
            microBreakDuration: microDuration > 0 ? microDuration : 20,
            macroBreakInterval: (macroInterval > 0 ? macroInterval : 60) * 60,
            macroBreakDuration: (macroDuration > 0 ? macroDuration : 5) * 60,
            mandatoryBreakInterval: (mandatoryInterval > 0 ? mandatoryInterval : 120) * 60,
            mandatoryBreakDuration: (mandatoryDuration > 0 ? mandatoryDuration : 15) * 60,
            isMicroBreakEnabled: true,
            isMacroBreakEnabled: true,
            isMandatoryBreakEnabled: true,
            isSoundEnabled: soundEnabled as? Bool ?? true,
            isEscalationEnabled: true,
            reminderMode: reminderMode
        )
    }

    /// Whether auto-generate daily report is enabled.
    static var isAutoReportEnabled: Bool {
        let value = UserDefaults.standard.object(forKey: "autoGenerateDailyReport")
        return value as? Bool ?? true
    }

    /// Whether launch at login is enabled.
    static var isLaunchAtLoginEnabled: Bool {
        UserDefaults.standard.bool(forKey: "launchAtLogin")
    }
}
